name: Publish Starters
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex
    steps:
      - uses: actions/checkout@v2
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@master
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB2 }}
        with:
          source-directory: 'protos'
          destination-github-username: 'JolleJ'
          destination-repository-name: 'testAction'
          user-email: joeljansson96@gmail.com
