# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Pushes to another repository
      uses: JolleJ/beerdev_protos@master
      env: 
        API_TOKEN_GITHUB: ${{ secrets.CI_TOKEN }}
      with:
          source-directory: 'protos'
          destination-github-username: 'JolleJ'
          destination-repository-name: 'grpc_node'
          user-email: JoelJansson96@gmail.com
