# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Create local changes
      run: |
        ...
    - name: Commit files2
      run: |
        git config --local user.email "JoelJansson96@gmail.com"
        git config --local user.name "JolleJ"
        git commit -m "Add changes" -a
    - name: Push changes
      uses: JolleJ/grpc_node@master
      with:
        github_token: ${{ secrets.CI_TOKEN }}
