# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@master
    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: git@github.com:JolleJ/grpc_node.git
        BRANCH: master
        FOLDER: protos
        SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY2 }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
